# @name login
POST {{API_HOST}}/login
content-type: application/json

{
    "user": "admin",
    "password": "password"
}

###

@token={{login.response.body.auth.token}}

# @name profile
GET {{API_HOST}}/profile
authorization: {{token}}

###

# @name todo_list
GET {{API_HOST}}/todo
authorization: {{token}}


###

# @name todo_create
POST {{API_HOST}}/todo
authorization: {{token}}
content-type: application/json

{
    "title": "title",
    "description": "desc"
}

###

@todoId=828c6204-4c30-4522-b9a6-985b5fa40025
# @name todo_items
GET {{API_HOST}}/todo/{{todoId}}
authorization: {{token}}
content-type: application/json

###

# @name todo_items_create
POST {{API_HOST}}/todo/{{todoId}}
authorization: {{token}}
content-type: application/json

{
    "title": "item2"
}


