# @name login
POST {{API_HOST}}/login
content-type: application/json

{
    "user": "admin",
    "password": "password"
}

###

@token={{login.response.body.auth.token}}

# @name profile
GET {{API_HOST}}/profile
authorization: {{token}}